"use client";

import { useState } from "react";
import { Sidebar } from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Menu, X } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [sidebarOpen, setSidebarOpen] = useState(true);

  return (
    <html lang="en" className="antialiased">
      <body className={inter.className}>
        <div className="grid min-h-screen grid-cols-app">
          {/* Sidebar com largura condicional e responsiva */}
          <aside
            className={`border-r border-zinc-200 bg-white transition-all duration-300
              ${sidebarOpen ? "max-w-64" : "max-w-0 overflow-hidden"}
              md:max-w-none md:w-64 md:overflow-visible
            `}
          >
            <Sidebar activeMenu={""} onSelectMenu={function (menu: string): void {
              throw new Error("Function not implemented.");
            } } />
          </aside>

          {/* Main com botão para abrir/fechar sidebar */}
          <main className="px-8 pb-12 pt-8 relative flex flex-col">
            <button
              onClick={() => setSidebarOpen(!sidebarOpen)}
              className="mb-4 md:hidden text-zinc-600 hover:text-zinc-900"
              aria-label="Toggle Sidebar"
            >
              {sidebarOpen ? <X size={24} /> : <Menu size={24} />}
            </button>

            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
